stages:
  protein_sequence_table:
    cmd: python3 P1_TableGenerator.py
    deps:
    - P1_TableGenerator.py
    - data/refseq
    outs:
    - ./data/seq_dic.tsv
  protein_sequence_fasta:
    cmd: bash P2_Table2Fasta
    deps:
    - ./data/seq_dic.tsv
    - P2_Table2Fasta
    outs:
    - ./data/seq_dic.fasta
