name: thermalizer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - mmtf-python
  - python-levenshtein
  - beautifulsoup4
  - ca-certificates
  - certifi
  - cython
  - freetype
  - fuzzywuzzy
  - jpeg
  - libpng
  - libtiff
  - msgpack-python
  - ncurses
  - nose
  - ncbi-datasets-cli
  - olefile
  - openssl
  - python>=3.8
  - pandas
  - pillow
  - pip
  - python-dateutil
  - pytz
  - readline
  - reportlab
  - setuptools
  - six
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - intel-openmp
  - mkl
  - numpy
  - pip:
    - msgpack
    - dvc[ssh]


